PORT=5000
FRONTEND_URL=http://localhost:3000
BACKEND_URL=https://legal-camels-talk.loca.lt
CLERK_SECRET_KEY=sk_test_U7ChRHu0ncBbOOLSshRvSOc2yWS22bf8k0LCwUQkD7
APP_ENCRYPTION_KEY=marketplace-hub-local-dev-encryption-key
TIKTOK_STATE_SECRET=marketplace-hub-tiktok-state-secret
TIKTOK_CLIENT_KEY=sbaw4o91lsxzp9bx4r
TIKTOK_CLIENT_SECRET=CLZCFJOXPlY8TFgHH6YfdfF6wedMRzJl
TIKTOK_REDIRECT_URI=https://legal-camels-talk.loca.lt/api/integrations/tiktok/callback
TIKTOK_SCOPES=user.info.basic
STRIPE_SECRET_KEY=sk_test_51SlAZRELtHOo4iKHl3ZGOs9y5C43CWmnySRmiazs7Wc5c290dD8LwZZGnc2FgxHFG1oClDXjKIqkryM6vNuIW4co00MFusE5F4
STRIPE_WEBHOOK_SECRET=whsec_REPLACE_WITH_YOUR_STRIPE_WEBHOOK_SECRET
STRIPE_CONNECT_RETURN_URL=http://localhost:3000/launch-pad
STRIPE_CONNECT_REFRESH_URL=http://localhost:3000/launch-pad


